# This is where we start, this is the existing image we start from, as below ubuntu + python
FROM python:3.14-slim
# Sets the working directory inside the image created ^
WORKDIR /app 
# Copy the files from the build context, to the image -> here we're copying req.txt and root .
COPY requirements.txt .
# Invoke a shell inside the image -> run the below command
RUN pip install -no-cache-dir -r requirements.txt

COPY . . 
# Mirrors ENTRYPOINT -> This command will run when the container starts, 
# CMD is what the container actually needs to do,
# everything else is being built before it runs
CMD ["python", "src/main.py"]
# ENTRYPOINT VS CMD: EP is a fixed executable, CMD is the default and args given to docker run, use CMD. 



